{
  "swagger": "2.0",
  "info": {
    "description": "Test Serverless API",
    "title": "<NODE_ENV>-api-gateway-proxy"
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/api/user/login": {
      "post": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "POST",
          "uri":"<USER_URL>/login"
        }
      }
    },
    "/api/user/profile": {
      "get": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "GET",
          "uri":"<USER_URL>/profile"
        }
      }
    },
    "/api/user/getProfile": {
      "get": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "GET",
          "uri":"<DOMAIN_URL>/api/user/getProfile"
        }
      }
    },
    "/api/user/updateProfile": {
      "post": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "POST",
          "uri":"<DOMAIN_URL>/api/user/updateProfile"
        }
      }
    },
    "/api/user/updatePassword": {
      "post": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "POST",
          "uri":"<DOMAIN_URL>/api/user/updatePassword"
        }
      }
    },
    "/api/user/updatePasswordViaForgotLink": {
      "post": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "POST",
          "uri":"<DOMAIN_URL>/api/user/updatePasswordViaForgotLink"
        }
      }
    },
    "/api/user/updateProfilePic": {
      "post": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "POST",
          "uri":"<DOMAIN_URL>/api/user/updateProfilePic"
        }
      }
    },
    "/api/user/updateSettings": {
      "post": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "POST",
          "uri":"<DOMAIN_URL>/api/user/updateSettings"
        }
      }
    },
    "/api/user/forgotPassword": {
      "post": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "POST",
          "uri":"<DOMAIN_URL>/api/user/forgotPassword"
        }
      }
    },
    "/api/user/verifyPasswordResetLink": {
      "post": {
        "produces": [
          "application/json"
        ],
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "POST",
          "uri":"<DOMAIN_URL>/api/user/verifyPasswordResetLink"
        }
      }
    },
    "/api/cancellations/listRefundModes/{bookingId}/{flightId}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "requestParameters": {
           "integration.request.path.bookingId": "method.request.path.bookingId",
           "integration.request.path.flightId": "method.request.path.flightId"
        },
        "responses": {},
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "GET",
          "uri":"<DOMAIN_URL>/api/cancellations/listRefundModes/{bookingId}/{flightId}"
        }
      }
    },
    "/{proxy+}": {
      "x-amazon-apigateway-any-method": {
        "description": "Test API",
        "x-amazon-apigateway-integration": {
          "passthroughBehavior": "WHEN_NO_MATCH",
          "type": "HTTP_PROXY",
          "httpMethod": "ANY",
          "uri":"https://<NODE_ENV>-server-admin.udchalo.com"
        }
      }
    }
  }
}
